settings:
  plugins:
    ckeditor5_codeBlock:
      languages:
        0:
          label: 'Text pla'
        1:
          label: C
        4:
          label: CSS
        5:
          label: Diferència
        6:
          label: HTML
        8:
          label: JavaScript
        9:
          label: PHP
        10:
          label: Python
        11:
          label: Ruby
        13:
          label: XML
