_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: a4b3d956-d058-41b6-ae37-ac84837f0958
name: KaniKat.com
mail: admin@example.com
slogan: 'La millor alimentació'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
